config/routes.rb
Rails.application.routes.draw do
  resources :letters
  root 'letters#index'

end

app/models/letter.rb
class Letter < ActiveRecord::Base

	validates :recipient_first_name, presence: true
	validates :recipient_last_name, presence: true
	validates :recipient_street, presence: true
	validates :recipient_state, presence: true
	validates :recipient_city, presence: true
	validates :recipient_zip, presence: true
	validates :content, presence: true, 
						length: {maximum: 250}
	


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/letters_controller.rb
class LettersController < ApplicationController
  before_action :set_letter, only: [:show, :edit, :update, :destroy]

  # GET /letters
  # GET /letters.json
  def index
    @letters = Letter.all
  end

  # GET /letters/1
  # GET /letters/1.json
  def show
  end

  # GET /letters/new
  def new
    @letter = Letter.new
  end

  # GET /letters/1/edit
  def edit
  end

  # POST /letters
  # POST /letters.json
  def create
    @letter = Letter.new(letter_params)

    respond_to do |format|
      if @letter.save
        format.html { redirect_to @letter, notice: 'Letter was successfully created.' }
        format.json { render :show, status: :created, location: @letter }
      else
        format.html { render :new }
        format.json { render json: @letter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /letters/1
  # PATCH/PUT /letters/1.json
  def update
    respond_to do |format|
      if @letter.update(letter_params)
        format.html { redirect_to @letter, notice: 'Letter was successfully updated.' }
        format.json { render :show, status: :ok, location: @letter }
      else
        format.html { render :edit }
        format.json { render json: @letter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /letters/1
  # DELETE /letters/1.json
  def destroy
    @letter.destroy
    respond_to do |format|
      format.html { redirect_to letters_url }
      format.json { head :no_content }
    end
  end

  #Lob

  def send_letter
    @lob = Lob(api_key: "test_aef982f552057fc81ccc43a2b14e106ebe3")
    @lob.jobs.create(
      name: "Inline Test Job",
        from: {
        name: "Ryan Goins",
        address_line1: "924 S Westnedge Ave",
        city: "Kalamazoo",
        state: "MI",
        country: "US",
        zip: 48329
      },
      to: {
        name: params[:recipient_first_name][:recipient_last_name]
        address_line1: params[:recipient_street],
        city: params[:recipient_city],
        state: params[:recipient_state],
        country: "US",
        zip: params[:recipient_zip]
      }
       front: "https://www.lob.com/postcardback.pdf",
       message: "Hey Ryan, you did it! Your first letter!"
    )
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_letter
      @letter = Letter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def letter_params
      params.require(:letter).permit(:recipient_first_name, :recipient_last_name, :recipient_street, :recipient_city, :recipient_state, :recipient_zip, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/letters_helper.rb
module LettersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Letters</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/letters/_form.html.erb
<%= form_for(@letter) do |f| %>
  <% if @letter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@letter.errors.count, "error") %> prohibited this letter from being saved:</h2>

      <ul>
      <% @letter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :recipient_first_name %><br>
    <%= f.text_field :recipient_first_name %>
  </div>
  <div class="field">
    <%= f.label :recipient_last_name %><br>
    <%= f.text_field :recipient_last_name %>
  </div>
  <div class="field">
    <%= f.label :recipient_street %><br>
    <%= f.text_field :recipient_street %>
  </div>
  <div class="field">
    <%= f.label :recipient_city %><br>
    <%= f.text_field :recipient_city %>
  </div>
  <div class="field">
    <%= f.label :recipient_state %><br>
    <%= f.text_field :recipient_state %>
  </div>
  <div class="field">
    <%= f.label :recipient_zip %><br>
    <%= f.number_field :recipient_zip %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/letters/edit.html.erb
<h1>Editing letter</h1>

<%= render 'form' %>

<%= link_to 'Show', @letter %> |
<%= link_to 'Back', letters_path %>

app/views/letters/index.html.erb
<h1>Listing letters</h1>

<table>
  <thead>
    <tr>
      <th>Recipient first name</th>
      <th>Recipeint last name</th>
      <th>Recipient street</th>
      <th>Recipient city</th>
      <th>Recipient state</th>
      <th>Recipient zip</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @letters.each do |letter| %>
      <tr>
        <td><%= letter.recipient_first_name %></td>
        <td><%= letter.recipient_last_name %></td>
        <td><%= letter.recipient_street %></td>
        <td><%= letter.recipient_city %></td>
        <td><%= letter.recipient_state %></td>
        <td><%= letter.recipient_zip %></td>
        <td><%= letter.content %></td>
        <td><%= link_to 'Show', letter %></td>
        <td><%= link_to 'Edit', edit_letter_path(letter) %></td>
        <td><%= link_to 'Destroy', letter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Letter', new_letter_path %>

app/views/letters/new.html.erb
<h1>New letter</h1>

<%= render 'form' %>

<%= link_to 'Back', letters_path %>

app/views/letters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recipient first name:</strong>
  <%= @letter.recipient_first_name %>
</p>

<p>
  <strong>Recipeint last name:</strong>
  <%= @letter.recipient_last_name %>
</p>

<p>
  <strong>Recipient street:</strong>
  <%= @letter.recipient_street %>
</p>

<p>
  <strong>Recipient city:</strong>
  <%= @letter.recipient_city %>
</p>

<p>
  <strong>Recipient state:</strong>
  <%= @letter.recipient_state %>
</p>

<p>
  <strong>Recipient zip:</strong>
  <%= @letter.recipient_zip %>
</p>

<p>
  <strong>Content:</strong>
  <%= @letter.content %>
</p>

<%= link_to 'Edit', edit_letter_path(@letter) %> |
<%= link_to 'Back', letters_path %>